name: Build Windows EXE (cross-compile)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Build test.exe
        run: |
          x86_64-w64-mingw32-gcc src/main.c -o test.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: test-windows-exe
          path: test.exe